# Generated by Django 3.1.5 on 2021-01-21 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usersignupdb_dateofreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupdb',
            name='dateOfReg',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
