# Generated by Django 3.1.5 on 2021-01-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210121_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patienteye', models.ImageField(blank=True, upload_to='retinal_scan')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usersignupdb')),
            ],
        ),
    ]
