# Generated by Django 3.1.5 on 2021-02-06 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210123_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignupdb',
            name='dateOfReg',
        ),
        migrations.AddField(
            model_name='userimage',
            name='dateOfReg',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userimage',
            name='timeOfReg',
            field=models.TimeField(default=datetime.time(12, 10, 15, 58533)),
        ),
    ]
