# Generated by Django 3.1.5 on 2021-02-06 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210206_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='dateOfReg',
            new_name='dateOfUpload',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='timeOfReg',
        ),
        migrations.AddField(
            model_name='userimage',
            name='timeOfUpload',
            field=models.TimeField(default=datetime.time(12, 31, 6, 205089)),
        ),
    ]
